import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { FridgeProvider } from "@/context/fridgeContext.context";
import { ShoppingListProvider } from "@/context/shoppingListContext.context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <FridgeProvider>
        <ShoppingListProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
            >
              <Header />
              <div className="flex-1 overflow-auto">
                {children}
              </div>
            </body>
          </html>
        </ShoppingListProvider>
      </FridgeProvider>
    </ClerkProvider>
  );
}